### PR TITLE
Closes #16

### LINKED ISSUE #16: Adding a Piranha Plant
Implement all the interaction and turtle shell features of a Piranha Plant. Here is some information based on [Mario Wiki](https://www.mariowiki.com/Piranha_Plant).

1. ~~The Piranha Plants inhabit pipes and attack by biting Mario or Luigi if they come into contact with these carnivorous plants.~~
2. ~~Piranha Plants will not emerge from their pipe if Mario or Luigi are adjacent to or standing directly on top of it, similar to a Bill Blaster.~~
3. Piranha Plants can be defeated by:
   - ~~Shooting them with a fireball~~
   - Kicking a Koopa Troopa or Buzzy Beetle shell at them
   - Touching them while empowered by a Starman

Update (Mar. 1, 2021): No. 1, 2 and partially 3 are completed. This issue is keep opened due to in completed tasks.

### PR DESCRIPTION
**Pull request by dlbjames**
# Pull Request Description

close #16 

Please fill out the form below. For the checkbox, use [x] to have a checkmark. For example:

- [x] With a checkmark.
- [ ] Without a checkmark.

This should not affect the way whether your pull request is accepted or not. Think of it like a survey and documentation, so the reviewers and future developers can follow your PR easier.

1. Have you included *.gitignore* file? Or manually remove config and environment files (E.g: *node_modules* folder, Eclipse IDE files) from this submission? The answer should be **Yes** in this case.

   - [x] Yes
   - [ ] No

2. Did you fully complete the assigned task(s)?

   - [x] Fully completed
   - [ ] Partially completed

3. Did you introduce a new non-required feature in this PR? This feature is not an assigned task, but it is the one that you feel will make the game better. For example, reproduce a bug used by speed runner in an original version.

   - [x] Yes
   - [ ] No

4. Are you aware of any bug caused by your code that have not been fixed in this PR?

   - [ ] Yes
   - [x] No

5. Are you aware of any **potential bug**? You don't have to fix this, it is just a way to document. You may not face the bug during the development process, but theoretically it can happens in edge cases. For example, memory leak or a player falls out of map.

   - [x] Yes
   - [ ] No

## Unimplented task(s)

- *Only answer when you chose **Partially completed** in question 2, provide a brief summary of what you have not done in here.*

## Related issue(s)

- 16
- Added the option for the Tube to determine what types of enemies it will spawn (piranha, coins, mushrooms, goombas, etc.). Currently only spawns piranha plants, but can be adapted for the other entities if needed later.

## Added

- Piranha Plant.
- Piranha Plants do not emerge from the tubes if Mario is standing too close to the tube.
- Piranha Plants give a score of 200 to Mario when he defeats them

## Changed and Enhanced

- Added an optional parameter for the Tube constructor which can determine what enemies spawn from it

## Fixed

- N / A

## Bugs

1. Not-fixed bugs (only answer when you chose **Yes** in question 4):
   - N / A
2. Potential bugs (only answer when you chose **Yes** in question 5):
   - Game Crashes when Mario enters a Tube too fast (Present before the additions)
   - Mushrooms get stuck inside of Goombas instead of passing through them after just emerging (Present before additions)

## Contributors and code author(s)

- Darryl James

## Final check

Have you fully filled out this document, and add a label **PR: NEED REVIEW** to this pull request? Answer *Yes* (as it should be) means you are good to go! Thanks for the contribution.

- [x] Yes
- [ ] No

### CODE REVIEW

**Review by BenjaminDeJager — APPROVED** [review]
I have not checked if this code works, so I'd say as long as it doesn't break the code this is fine.

It looks good and seems like a pretty clean implementation of how the prana plant works. also good eye on making sure the thing doesn't show up if mario is too close, I forgot that was a thing

https://www.mariowiki.com/Piranha_Plant#Super_Mario_Bros.
image

**Comment by dlbjames** [comment]
Thank you thank you! The implementation was working on my end with vsCode, but I am not sure if it passes the test cases you guys have set up since I can not see those 😬. In short, nothing should break relating to the piranha plant.

**Comment by hunghvu** [comment]
@dlbjames 
> Thank you thank you! The implementation was working on my end with vsCode, but I am not sure if it passes the test cases you guys have set up since I can not see those 😬. In short, nothing should break relating to the piranha plant.

You're right, the test case is not running because I set it to run on **main** while we have **master** here. I guess we can just forget the test for now.

**Review by hunghvu — APPROVED** [review]
I cannot see the piranha when staying on your branch. My guess is you only implemented the object, but not put them on the map, which is fine. The following review is purely by looking at your code.

According to #16.
1. It seems like your code does not implement attacking mechanism for the Piranha plant.
2. The emerging mechanism seems to work fine. 
3. It seems like there is no "being defeated" mechanism.

I will approve this PR, but do note that as there seems to be incompleted tasks so I will consider this PR as **partially completed**. Besides, the final evaluation of your contribution will be made by Chris.

**Pull request merged**
