### PR TITLE
added level 1-2 underground + bonus layout

### LINKED ISSUE #13: Adding map layouts and moving obstacles for world 1
You have to populate the layout and all objects in worlds ~~1-1, 1-2~~, 1-3, and 1-4. Please work on the existed entities first. Throughout the time, new entities may be added. Please consider merging the master branch to yours and update world 1 with new entities.

Update (Mar. 1, 2021): World 1-1 and 1-2 are completed. Do note it's only about map layout, not all entities are implemented. This issue will be keep opened due to in-completed tasks.

### PR DESCRIPTION
**Pull request by hieuc**
# Pull Request Description

Please fill out the form below. For the checkbox, use [x] to have a checkmark. For example:

- [x] With a checkmark.
- [ ] Without a checkmark.

This should not affect the way whether your pull request is accepted or not. Think of it like a survey and documentation, so the reviewers and future developers can follow your PR easier.

1. Have you included *.gitignore* file? Or manually remove config and environment files (E.g: *node_modules* folder, Eclipse IDE files) from this submission? The answer should be **Yes** in this case.

   - [x] Yes
   - [ ] No

2. Did you fully complete the assigned task(s)?

   - [ ] Fully completed 
   - [x] Partially completed

3. Did you introduce a new non-required feature in this PR? This feature is not an assigned task, but it is the one that you feel will make the game better. For example, reproduce a bug used by speed runner in an original version.

   - [ ] Yes
   - [x] No

4. Are you aware of any bug caused by your code that have not been fixed in this PR?

   - [ ] Yes
   - [x] No

5. Are you aware of any **potential bug**? You don't have to fix this, it is just a way to document. You may not face the bug during the development process, but theoretically it can happens in edge cases. For example, memory leak or a player falls out of map.

   - [ ] Yes
   - [x] No

## Unimplented task(s)

- Level 1-2 also has 2 overworld parts which act as intro and outro. Layouts for these were not included.

## Related issue(s)

- Level transition (tubes to bonus level and tubes back to main level) was not implemented (not in the scope of this task). Attempting to enter a tube will transition back to level 1-1.
- Missing starman (invincibility) powerup, currently replaced with a shroom.
- Missing moving platforms.

## Added

- *Level 1-2 underground (main map) layout.*
- *Level 1-2 bonus level (under first tube of main map) layout.*

## Changed and Enhanced

- None
## Fixed

- None

## Bugs

1. Not-fixed bugs (only answer when you chose **Yes** in question 4):
   - None
2. Potential bugs (only answer when you chose **Yes** in question 5):
   - None

## Contributors and code author(s)

- Victor Chau

## Final check

Have you fully filled out this document, and add a label **PR: NEED REVIEW** to this pull request? Answer *Yes* (as it should be) means you are good to go! Thanks for the contribution.

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by hunghvu** [comment]
Can you please show me a way to access world 1-2?

**Comment by hieuc** [comment]
> Can you please show me a way to access world 1-2?

In sceneManager.js line 16, change param levelOne to levelTwo, this will load the level on start.

**Comment by hunghvu** [comment]
Sorry for not asking this, how can we access bonus level? Is there any other level that I'm missing?

**Comment by hieuc** [comment]
> Sorry for not asking this, how can we access bonus level? Is there any other level that I'm missing?

The same method should work: change levelOne to bonusLevelTwo. That's all the 2 levels for this commit. I didn't handle the level transition so the tubes in both these levels will lead back to level 1-1.

**Comment by hunghvu** [comment]
Another apology for my ignorant question... In your implementation, when going down the first tube, Mario will go to *left level* in the pictuer. However, some video on Youtube suggests that the tube should lead to your bonus level. Why is that? Here is the link to Youtube video https://www.youtube.com/watch?v=fJPdDCsROik&ab_channel=JannisXxL
image

**Comment by hieuc** [comment]
> Another apology for my ignorant question... In your implementation, when going down the first tube, Mario will go to _left level_ in the pictuer. However, some video on Youtube suggests that the tube should lead to your bonus level. Why is that? Here is the link to Youtube video https://www.youtube.com/watch?v=fJPdDCsROik&ab_channel=JannisXxL
> image

This is happening as expected. This commit only changed levels.js file. Level transition is handled in sceneManager.js and it was untouched, hence the disconnect in level transition.

**Review by hunghvu — APPROVED** [review]
Looks good to me. There is a catch though. I think the ground is supposed to be attached to bottom of canvas, not floating as shown in the picture. It's a minor bug so it's fine.

I will approve this PR because no game breaking bug is detected.
image

**Review by BenjaminDeJager — APPROVED** [review]
not directly relevant to this pr per-say, but please see issue %37 on moving platforms as they exist on the bonus level irrc.

**Pull request merged**
