### PR TITLE
Added the koopa shell to the game

### LINKED ISSUE #14: Adding a turtle shell state to Koopa
Implement all the interaction and turtle shell features of Koopa. Here is some information based on [Mario Wiki](https://www.mariowiki.com/Koopa_Troopa).

1. If a Mario lands on a Koopa, the Koopa hides in its shell.
2. The shell can be kicked around and bounced off obstacles.
3. The shell can be used to attack enemies.
4. Super Mario and Fire Mario are revert to normal form if they get hit by the shell. A normal Mario will die instead.
5. The Koopa reemerges if a shell stays alone for too long.

Update: As of 02/22/2021, No 1-2-5 are completed. No. 3 and 4 are still not implemented so this issue will be kept opened.

### PR DESCRIPTION
**Pull request by obver-se**
# Pull Request Description

1. Have you included *.gitignore* file? Or manually remove config and environment files (E.g: *node_modules* folder, Eclipse IDE files) from this submission? The answer should be **Yes** in this case.

   - [ ] Yes
   - [x] No

2. Did you fully complete the assigned task(s)?

   - [x] Fully completed
   - [ ] Partially completed

3. Did you introduce a new non-required feature in this PR? This feature is not an assigned task, but it is the one that you feel will make the game better. For example, reproduce a bug used by speed runner in an original version.

   - [ ] Yes
   - [x] No

4. Are you aware of any bug caused by your code that have not been fixed in this PR?

   - [ ] Yes
   - [x] No

5. Are you aware of any **potential bugs**? You don't have to fix this, it is just a way to document. You may not face the bug during the development process, but theoretically it can happens in edge cases. For example, memory leak or a player falls out of map.

   - [ ] Yes
   - [x] No

## Unimplemented task(s)

N/A

## Related issue(s)

#14 

## Added

The KoopaShell entity now spawns when ever the Koopa is stomped. It goes back and forth when it hits things and can be started and stopped by jumping on it or started by walking into it.

## Changed and Enhanced

The Koopa class now spawns a KoopaShell when stomped.

## Fixed

N/A

## Bugs

N/A

## Contributors and code author(s)

@obver-se - Daniel Machen

## Final check

Have you fully filled out this document, and add a label **PR: NEED REVIEW** to this pull request? Answer *Yes* (as it should be) means you are good to go! Thanks for the contribution.

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by hunghvu** [comment]
@obver-se You may want to use your real name for **Contributors and code author(s)**.

**Review by hunghvu — APPROVED** [review]
Looks good to me. Based on the issue, seems like ~~No. 3 and 5~~ No. 3 and 4 are not implemented. Although, it's also fair to say that is those collision should be implemented in their respective entity instead (E.g: Mario, Enemy, etc), but for the sake of this issue, I will consider this PR *partially completed*. You do not have to complete all tasks so that's fine.

Besides, I notice whenever an enemy fall out of map, it does not disappear but keep falling down to infinity. This is a minor bug so you don't need to fix. In fact, the Goombas also have this issue. You can notice the bug at around 0:15 - 0:20 in the video, pay attention to the mini map. 

I will approve this PR as no game breaking bug is detected.


https://user-images.githubusercontent.com/62678592/108787407-84adf000-752a-11eb-81c4-c0afa74ba88f.mp4

**Comment by obver-se** [comment]
Did you try to test feature 5? The turtle should come out of its shell if it stays still long enough. You're right though 3 is not implemented.

**Comment by hunghvu** [comment]
> Did you try to test feature 5? The turtle should come out of its shell if it stays still long enough. You're right though 3 is not implemented.

My bad, they are No. 3 and 4, No. 5 works. I edited my comment above.

**Review by BenjaminDeJager — APPROVED** [review]
seems like a pretty good implementation of the koopa shell and I see no potential for future conflicts. 

I would suggest more comment code however even if the majority of this is pretty obvious.

**Pull request merged**
